### ISSUE TITLE
Show date instead of datetime

### ISSUE THREAD

**Issue by JohannesPtaszyk** [Nazze/ha_best_bottrop_garbage_collection#2]
Would be awesome if we would have a way to only show date instead of date + time in Lovelace as only date is really relevant 🤔
Since I migrated from openhab I have no clue if this can easily done or we would have to implement it here. 

Anyways, thanks for the great integration :)

**Comment by Nazze** [comment]
Hi! Thanks for your feedback. I will check and get back.

**Comment by Nazze** [comment]
#3

**Comment by Nazze** [comment]
Fixed in version 0.24 with PR #3  . Thanks for the feedback. I hope, this integration is useful for you.

**Comment by JohannesPtaszyk** [comment]
Yes, I was so excited to find this ❤️
