### ISSUE TITLE
Ignore days are reset after restart the integration 

### ISSUE THREAD

**Issue by Lucker03** [Nazze/ha_best_bottrop_garbage_collection#7]
First of all, thanks for the nice integration. I like this feature. But when I use the ignore state, sometimes the ignore value is reset. I can reproduce this when I reload the integration, but sometimes this happens without reloading.

Start value:
![image](https://github.com/user-attachments/assets/16ebbc28-9d79-473e-bf14-8412d30c9e3a)

After ignore:
![image](https://github.com/user-attachments/assets/c73ec5d6-037b-4cbf-a244-a1bc1591c9c8)

After reload:
![image](https://github.com/user-attachments/assets/bdae4113-9b6f-4152-a8c4-ac37d17621de)

I would help to find the error, but I am not good at programming with Python. :)

**Comment by Nazze** [comment]
Hi! Thanks for your feedback! Glad, you like it. I am aware that the ignore_until is not persistant after reload of the integration or a reboot. But I was not aware that this could also happen sporadically. I will look into this and make it persistant. Hope I can do it still in September, if this is OK.

**Comment by Lucker03** [comment]
Ich nehme mal an, dass du auch Deutsch sprichst, da die Integration nur für Bottrop geht😅 Habe nur aus Gewohnheit englisch geschrieben.

Ich lade mein Home Assistant relativ häufig neu, vielleicht liegt es auch daran. Ich werde da die nächsten Tage mal drauf achten. 

Falls ich dir irgendwie helfen kann, kannst du gerne fragen. Bin selber nur nicht so gut in Python und Home Assistant Programmierung, würde das aber gerne mal lernen. :)

**Comment by Nazze** [comment]
Ja, komme ja auch aus Bottrop :-D
Ich denke, dass Homeassistant nicht das einfachste Projekt ist, um Python zu lernen. Es gibt da viele kostenlose Tutorials im Netz. Wenn Du in die Python-Programmierung einsteigen willst, wäre das vermutlich der beste Weg. LG

**Comment by Nazze** [comment]
Moin! Ich denke, ich habe das Problem gelöst. Muss noch etwas den Code aufräumen und testen. Aber spätestens nächste Woche gibt es ein Update 😀🎉

**Comment by Lucker03** [comment]
Thema Python lernen: Ja, das ist mir auch aufgefallen, dass das mit Home Assistant etwas schwieriger ist. Das Problem ist nur, dass ich, wenn ich Programmiere, auch etwas machen möchte, was ich nachher nutzten kann. Und da ich generell Programmieren kann, dachte ich, dass das relativ einfach sein sollte, aber irgendwie komme ich mit der Doku und den Tutorials nicht so gut klar. 

Da freue ich mich drauf 😍 (Mir ist aufgefallen, dass es doch nur beim Neustarten von dem Home Assistant passiert. Nur da ich häufig mein HA neu starte, passiert das relativ häufig)

**Comment by Nazze** [comment]
Also ich muss auch sagen, dass die Doku bei HA einfach total unvollständig ist. Ich musste mich jetzt auch durch fremden Code durcharbeiten oder debuggen, um es irgendwie zu raffen. Schade eigentlich.

Schau mal, ich habe eine neue beta rausgegeben. Musst Du unter HACS besonders herunterladen (je nach HACS version sieht das unterschiedlich aus). Ist v.30_beta. Wäre nett, wenn Du mir eine Rückmeldung geben könntest, ob das nun funktioniert. Bis dahin.

**Comment by Lucker03** [comment]
Ja, das stimmt. Und wirkliche Youtube Tutorials gibt es auch nicht. 

Richtig cool, dass es so schnell ging. Habs installiert 👍Direkt nach dem Installieren und neu starten des HA konnte ich aber erstmal nicht über mein Dashboard das ignore setzten. Bzw. das wurde nicht im Dashboard angezeigt. Nachdem ich die Integration neu gestartet habe, ging es. Würde das aber dennoch ca. 1 Woche testen und mich dann noch mal melden, vielleicht war das auch einfach nur mein Dashboard.

**Comment by Nazze** [comment]
Komisch, gab es irgendwelcher Fehler im System Protokoll/Log?

**Comment by Lucker03** [comment]
Nein, ich könnte mir vorstellen, dass es eher ein Problem mit meinem Amazon Tablet war, dass dieser einfach nicht neu geladen hat.

**Comment by Nazze** [comment]
Ich habe schon einen Bug entdeckt. Nach dem aktualisieren des „ignore“ Werts, wird der Sensor nicht aktualisiert. Man muss die Integration neu laden. Ich mache heute noch eine neue Beta.

**Comment by Nazze** [comment]
Hallo! Das Problem sollte nun mit der v0.30 behoben sein. Es kann sein, dass dir die Release-Version nicht als Update angezeigt wird, wenn Du die beta hast. Dann musst Du vermutlich neu herunterladen. Inhaltlich gibt es aber keine Änderungen zwischen der Beta und der v0.30. Viel Spaß! Und freue mich über weiteres Feedback zur Integration. Beste Grüße und einen schönen Feiertag!
